# Site settings
title: SaibroTech
description: >- # this means to ignore newlines until "baseurl:"
  site.description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.saibro.tech" # the base hostname & protocol for your site
author: Copyright &copy; 2021 - SaibroTech
languages: ["pt-BR", "en"]

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-multiple-languages-plugin
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
  - vendor
  - .github
exclude_from_localizations: []
